# StackMarket Configuration File
#
# If this file is corrupted, delete it and restart the server to create a fresh one.
#
# All comments (lines ignored by server) are denoted with the # prefix such as this one.
# Please do not add or removing #s to existing lines.
#

#######################################################
# Database Configuration. Do not change unless needed.#
#######################################################
database:
  username: bukkit
  isolation: SERIALIZABLE
  driver: org.sqlite.JDBC
  password: walrus
  url: jdbc:sqlite:{DIR}{NAME}.db

#######################################################
# General Configuration.                              #
#######################################################

land:
  fixedmax: false
business:
  startcost:
    sole: 100
    llc: 250
    corp: 1000
stockmarket:
  public: true
  commission: 9
misc:
  defaultlistsort: date

# Refer to online documentation for information about the nodes.

donotchange:
  businesses:
  employees:
  jobs: