name: StackMarket
main: io.github.Battelman2.StackMarket.StackMarket
version: 0.0.1
commands:
  stackmarket:
      description: All commands belonging to StackMarket.
      usage: See /business help for list of commands available to you.
      aliases: [business, biz, company, market, sm, stack]
      permission: StackMarket.business
      permission-message: You don't have permission to use /business