name: Minecommerce
main: io.github.Battelman2.Minecommerce.Minecommerce
version: 1.0.0
commands:
  commerce:
      description: Displays status of Minecommerce.
      usage: /commerce
      permission: Minecommerce.commerce
      permission-message: You don't have permission to use /commerce